In [2]:
import numpy as np
import pandas as pd

In [3]:
np.random.seed(101)
mydata = np.random.randint(0,101,(4,3))

In [4]:
myindex = ['MH', 'KN', 'TN', 'WB']

In [5]:
print(mydata)

[[95 11 81]
 [70 63 87]
 [75  9 77]
 [40  4 63]]


In [6]:
attr = ['GDP', 'IT', 'REL']

In [7]:
df = pd.DataFrame(mydata)

In [8]:
df

0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63

In [9]:
pndf = pd.DataFrame(mydata, myindex, attr)

In [10]:
pndf

GDP  IT  REL
MH   95  11   81
KN   70  63   87
TN   75   9   77
WB   40   4   63

In [11]:
pndf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, MH to WB
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   GDP     4 non-null      int32
 1   IT      4 non-null      int32
 2   REL     4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes


In [12]:
df1 = pd.read_csv('example.csv')

In [13]:
df1

Index  Organization Id                     Name  \
0       1  FAB0d41d5b5d22c              Ferrell LLC   
1       2  6A7EdDEA9FaDC52  Mckinney, Riley and Day   
2       3  0bFED1ADAE4bcC1               Hester Ltd   
3       4  2bFC1Be8a4ce42f           Holder-Sellers   
4       5  9eE8A6a4Eb96C24              Mayer Group   
..    ...              ...                      ...   
95     96  0a0bfFbBbB8eC7c             Holmes Group   
96     97  BA6Cd9Dae2Efd62                 Good Ltd   
97     98  E7df80C60Abd7f9        Clements-Espinoza   
98     99  AFc285dbE2fEd24               Mendez Inc   
99    100  e9eB5A60Cef8354           Watkins-Kaiser   

                           Website                      Country  \
0               https://price.net/             Papua New Guinea   
1   http://www.hall-buchanan.info/                      Finland   
2        http://sullivan-reed.com/                        China   
3              https://becker.com/                 Turkmenistan   
4           http://www.brewer.com/                    Mauritius   
..                             ...                          ...   
95           https://mcdowell.org/                     Ethiopia   
96               http://duffy.com/                     Anguilla   
97         http://www.flowers.net/  Falkland Islands (Malvinas)   
98          https://www.burke.net/              Kyrgyz Republic   
99         http://www.herring.com/                         Togo   

                                       Description  Founded  \
0              Horizontal empowering knowledgebase     1990   
1              User-centric system-worthy leverage     2015   
2                   Switchable scalable moratorium     1971   
3   De-engineered systemic artificial intelligence     2004   
4               Synchronized needs-based challenge     1991   
..                                             ...      ...   
95          Right-sized zero tolerance focus group     1975   
96         Reverse-engineered composite moratorium     1971   
97                         Progressive modular hub     1991   
98                 User-friendly exuding migration     1993   
99                   Synergistic background access     2009   

                       Industry  Number of employees  
0                      Plastics                 3498  
1   Glass / Ceramics / Concrete                 4952  
2                 Public Safety                 5287  
3                    Automotive                  921  
4                Transportation                 7870  
..                          ...                  ...  
95                  Photography                 2988  
96            Consumer Services                 4292  
97              Broadcast Media                  236  
98         Education Management                  339  
99           Financial Services                 2785  

[100 rows x 9 columns]

In [14]:
df2 = pd.read_csv('C:\\Users\\prana\\Jupyter\\Python\\IndiaData.csv')

In [15]:
df2

countrycode country currency_unit  year       GDP  net population growth  \
0          IND   India  Indian Rupee  1979       NaN             682.995354   
1          IND   India  Indian Rupee  1980  5.281000               0.023364   
2          IND   India  Indian Rupee  1981  6.006000               0.023510   
3          IND   India  Indian Rupee  1982  3.476000               0.023560   
4          IND   India  Indian Rupee  1983  7.289000               0.023475   
5          IND   India  Indian Rupee  1984  3.821000               0.023224   
6          IND   India  Indian Rupee  1985  5.254000               0.022856   
7          IND   India  Indian Rupee  1986  4.777000               0.022458   
8          IND   India  Indian Rupee  1987  3.965000               0.022079   
9          IND   India  Indian Rupee  1988  9.628000               0.021700   
10         IND   India  Indian Rupee  1989  5.947000               0.021333   
11         IND   India  Indian Rupee  1990  5.534000               0.020978   
12         IND   India  Indian Rupee  1991  1.057000               0.020607   
13         IND   India  Indian Rupee  1992  5.482000               0.020234   
14         IND   India  Indian Rupee  1993  4.750000               0.019902   
15         IND   India  Indian Rupee  1994  6.659000               0.019622   
16         IND   India  Indian Rupee  1995  7.575000               0.019375   
17         IND   India  Indian Rupee  1996  7.550000               0.019133   
18         IND   India  Indian Rupee  1997  4.050000               0.018868   
19         IND   India  Indian Rupee  1998  6.184000               0.018567   
20         IND   India  Indian Rupee  1999  8.463000               0.018220   
21         IND   India  Indian Rupee  2000  3.975000               0.017838   
22         IND   India  Indian Rupee  2001  4.944000               0.017438   
23         IND   India  Indian Rupee  2002  3.907000               0.017039   
24         IND   India  Indian Rupee  2003  7.944000               0.016652   
25         IND   India  Indian Rupee  2004  7.849000               0.016284   
26         IND   India  Indian Rupee  2005  9.285000               0.015923   
27         IND   India  Indian Rupee  2006  9.264000               0.015577   
28         IND   India  Indian Rupee  2007  9.801000               0.015207   
29         IND   India  Indian Rupee  2008  6.013703               0.014757   
30         IND   India  Indian Rupee  2009  4.701769               0.014206   
31         IND   India  Indian Rupee  2010  6.377626               0.013595   
32         IND   India  Indian Rupee  2011  6.169784               0.012968   
33         IND   India  Indian Rupee  2012  6.030051               0.012391   
34         IND   India  Indian Rupee  2013  5.557264               0.011899   
35         IND   India  Indian Rupee  2014  5.006668               0.011523   
36         IND   India  Indian Rupee  2015  4.876322               0.011232   
37         IND   India  Indian Rupee  2016  5.033069               0.010964   
38         IND   India  Indian Rupee  2017  5.069786               0.010690   
39         IND   India  Indian Rupee  2018  5.174292               0.010432   
40         IND   India  Indian Rupee  2019  5.019288               0.010184   

          CPI  employment rate     labsh        xr  ...     csh_m      csh_r  \
0         NaN       256.839111  0.709059  8.125791  ... -0.027104  -0.063782   
1   11.346060         0.007102  0.038942 -0.032347  ...  0.311639  -0.235969   
2   13.112550         0.004508 -0.027032  0.101181  ...  0.171218  -0.391245   
3    7.890750         0.004125 -0.013325  0.092003  ... -0.227116   0.640088   
4   11.868070         0.003785  0.016143  0.068086  ...  0.568956  -0.435581   
5    8.318914         0.003513 -0.004469  0.125131  ... -0.186774   0.311368   
6    5.556426         0.003255 -0.023227  0.088551  ...  0.100199  -0.152234   
7    8.729712         0.004868 -0.004420  0.

In [16]:
df2.columns

Index(['countrycode', 'country', 'currency_unit', 'year', 'GDP',
       'net population growth', 'CPI', 'employment rate', 'labsh', 'xr',
       'pl_gdpo', 'csh_c', 'csh_i', 'csh_g', 'csh_x', 'csh_m', 'csh_r', 'pl_c',
       'pl_i', 'pl_g', 'pl_x', 'pl_m', 'pl_n', 'pl_k', 'GDP.1'],
      dtype='object')

In [17]:
df2.index

RangeIndex(start=0, stop=41, step=1)

In [18]:
df2.head(10)

countrycode country currency_unit  year    GDP  net population growth  \
0         IND   India  Indian Rupee  1979    NaN             682.995354   
1         IND   India  Indian Rupee  1980  5.281               0.023364   
2         IND   India  Indian Rupee  1981  6.006               0.023510   
3         IND   India  Indian Rupee  1982  3.476               0.023560   
4         IND   India  Indian Rupee  1983  7.289               0.023475   
5         IND   India  Indian Rupee  1984  3.821               0.023224   
6         IND   India  Indian Rupee  1985  5.254               0.022856   
7         IND   India  Indian Rupee  1986  4.777               0.022458   
8         IND   India  Indian Rupee  1987  3.965               0.022079   
9         IND   India  Indian Rupee  1988  9.628               0.021700   

         CPI  employment rate     labsh        xr  ...     csh_m     csh_r  \
0        NaN       256.839111  0.709059  8.125791  ... -0.027104 -0.063782   
1  11.346060         0.007102  0.038942 -0.032347  ...  0.311639 -0.235969   
2  13.112550         0.004508 -0.027032  0.101181  ...  0.171218 -0.391245   
3   7.890750         0.004125 -0.013325  0.092003  ... -0.227116  0.640088   
4  11.868070         0.003785  0.016143  0.068086  ...  0.568956 -0.435581   
5   8.318914         0.003513 -0.004469  0.125131  ... -0.186774  0.311368   
6   5.556426         0.003255 -0.023227  0.088551  ...  0.100199 -0.152234   
7   8.729712         0.004868 -0.004420  0.019572  ... -0.186842  0.336192   
8   8.801135         0.004824  0.004842  0.027807  ... -0.076174  0.281138   
9   9.383466         0.004898 -0.003169  0.073725  ...  0.005041 -0.108235   

       pl_c      pl_i      pl_g      pl_x      pl_m      pl_n      pl_k  GDP.1  
0  0.190954  0.224667  0.074652  0.292258  0.374884  0.140270  0.623519    NaN  
1  0.221119  0.115094  0.211470  0.029731  0.119947  0.198038  0.040884  5.281  
2  0.024342  0.200461  0.124758  0.062000 -0.101080  0.141719  0.044442  6.006  
3  0.022520  0.062986  0.090714  0.009650 -0.020343  0.142196  0.070686  3.476  
4  0.036162  0.053462  0.145769  0.073353 -0.117499  0.109214 -0.044686  7.289  
5 -0.020696  0.066587  0.043739 -0.000758  0.161264  0.079760 -0.070062  3.821  
6 -0.007321  0.094918  0.061442  0.020255  0.002747  0.070623  0.027706  5.254  
7  0.056895  0.023806  0.071507  0.109075  0.139978  0.046031  0.037279  4.777  
8  0.037346  0.049373  0.073591  0.086690  0.121913  0.100678  0.039696  3.965  
9  0.009976  0.015035  0.039840  0.077601  0.038810  0.025516  0.031666  9.628  

[10 rows x 25 columns]

In [19]:
df2.describe().transpose()

count         mean         std          min  \
year                    41.0  1999.000000   11.979149  1979.000000   
GDP                     40.0     5.868666    1.854317     1.057000   
net population growth   41.0    16.675493  106.663221     0.010184   
CPI                     40.0     7.902614    3.043830     2.490887   
employment rate         41.0     6.263619   40.111651    -0.017225   
labsh                   41.0     0.010039    0.113658    -0.065614   
xr                      41.0     0.254593    1.262023    -0.087370   
pl_gdpo                 41.0     0.021244    0.065271    -0.142609   
csh_c                   41.0     0.015728    0.106977    -0.044591   
csh_i                   41.0     0.018882    0.081396    -0.169636   
csh_g                   41.0    -0.020405    0.059846    -0.100470   
csh_x                   41.0     0.019582    0.080035    -0.132554   
csh_m                   41.0     0.036352    0.156437    -0.227116   
csh_r                   41.0    -0.115497    3.134763   -10.032102   
pl_c                    41.0     0.017192    0.068757    -0.139573   
pl_i                    41.0     0.019181    0.077100    -0.135302   
pl_g                    41.0     0.050118    0.069892    -0.112119   
pl_x                    41.0     0.029594    0.064973    -0.090891   
pl_m                    41.0     0.025775    0.088399    -0.117499   
pl_n                    41.0     0.015990    0.077446    -0.124870   
pl_k                    41.0     0.005179    0.114807    -0.159818   
GDP.1                   40.0     5.868666    1.854317     1.057000   

                               25%          50%          75%          max  
year                   1989.000000  1999.000000  2009.000000  2019.000000  
GDP                       4.851492     5.508000     6.816500     9.801000  
net population growth     0.014206     0.018220     0.021333   682.995354  
CPI                       5.402576     8.104832    10.230650    13.870250  
employment rate          -0.007974     0.003255     0.004868   256.839111  
labsh                    -0.020530    -0.004420     0.000000     0.709059  
xr                        0.027370     0.049949     0.096573     8.125791  
pl_gdpo                  -0.014644     0.017332     0.050503     0.191659  
csh_c                    -0.010980    -0.001110     0.015361     0.672914  
csh_i                    -0.034339     0.003695     0.085581     0.197984  
csh_g                    -0.054674    -0.029993     0.010016     0.224698  
csh_x                    -0.030599     0.010718     0.063934     0.209711  
csh_m                    -0.076174     0.016755     0.103303     0.568956  
csh_r                    -0.796965    -0.235969     0.281138    13.876584  
pl_c                     -0.014930     0.011703     0.042917     0.221119  
pl_i                     -0.026073     0.014385     0.067262     0.224667  
pl_g                      0.000161     0.053896     0.090714     0.211470  
pl_x                     -0.000758     0.020876     0.062000     0.292258  
pl_m                     -0.032542     0.028131     0.058451     0.374884  
pl_n                     -0.033910     0.005761     0.070623     0.198038  
pl_k                     -0.044686    -0.018257     0.039696     0.623519  
GDP.1                     4.851492     5.508000     6.816500     9.801000

In [20]:
arr = np.arange(0,25,1).reshape(5,5).transpose()

In [21]:
print(arr)

[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


In [22]:
df2.head(7)

countrycode country currency_unit  year    GDP  net population growth  \
0         IND   India  Indian Rupee  1979    NaN             682.995354   
1         IND   India  Indian Rupee  1980  5.281               0.023364   
2         IND   India  Indian Rupee  1981  6.006               0.023510   
3         IND   India  Indian Rupee  1982  3.476               0.023560   
4         IND   India  Indian Rupee  1983  7.289               0.023475   
5         IND   India  Indian Rupee  1984  3.821               0.023224   
6         IND   India  Indian Rupee  1985  5.254               0.022856   

         CPI  employment rate     labsh        xr  ...     csh_m     csh_r  \
0        NaN       256.839111  0.709059  8.125791  ... -0.027104 -0.063782   
1  11.346060         0.007102  0.038942 -0.032347  ...  0.311639 -0.235969   
2  13.112550         0.004508 -0.027032  0.101181  ...  0.171218 -0.391245   
3   7.890750         0.004125 -0.013325  0.092003  ... -0.227116  0.640088   
4  11.868070         0.003785  0.016143  0.068086  ...  0.568956 -0.435581   
5   8.318914         0.003513 -0.004469  0.125131  ... -0.186774  0.311368   
6   5.556426         0.003255 -0.023227  0.088551  ...  0.100199 -0.152234   

       pl_c      pl_i      pl_g      pl_x      pl_m      pl_n      pl_k  GDP.1  
0  0.190954  0.224667  0.074652  0.292258  0.374884  0.140270  0.623519    NaN  
1  0.221119  0.115094  0.211470  0.029731  0.119947  0.198038  0.040884  5.281  
2  0.024342  0.200461  0.124758  0.062000 -0.101080  0.141719  0.044442  6.006  
3  0.022520  0.062986  0.090714  0.009650 -0.020343  0.142196  0.070686  3.476  
4  0.036162  0.053462  0.145769  0.073353 -0.117499  0.109214 -0.044686  7.289  
5 -0.020696  0.066587  0.043739 -0.000758  0.161264  0.079760 -0.070062  3.821  
6 -0.007321  0.094918  0.061442  0.020255  0.002747  0.070623  0.027706  5.254  

[7 rows x 25 columns]

In [23]:
col = ['year', 'GDP']

In [24]:
df2[col]

year       GDP
0   1979       NaN
1   1980  5.281000
2   1981  6.006000
3   1982  3.476000
4   1983  7.289000
5   1984  3.821000
6   1985  5.254000
7   1986  4.777000
8   1987  3.965000
9   1988  9.628000
10  1989  5.947000
11  1990  5.534000
12  1991  1.057000
13  1992  5.482000
14  1993  4.750000
15  1994  6.659000
16  1995  7.575000
17  1996  7.550000
18  1997  4.050000
19  1998  6.184000
20  1999  8.463000
21  2000  3.975000
22  2001  4.944000
23  2002  3.907000
24  2003  7.944000
25  2004  7.849000
26  2005  9.285000
27  2006  9.264000
28  2007  9.801000
29  2008  6.013703
30  2009  4.701769
31  2010  6.377626
32  2011  6.169784
33  2012  6.030051
34  2013  5.557264
35  2014  5.006668
36  2015  4.876322
37  2016  5.033069
38  2017  5.069786
39  2018  5.174292
40  2019  5.019288

In [25]:
0.5 * (df2['GDP'] + df2['GDP.1'])

0          NaN
1     5.281000
2     6.006000
3     3.476000
4     7.289000
5     3.821000
6     5.254000
7     4.777000
8     3.965000
9     9.628000
10    5.947000
11    5.534000
12    1.057000
13    5.482000
14    4.750000
15    6.659000
16    7.575000
17    7.550000
18    4.050000
19    6.184000
20    8.463000
21    3.975000
22    4.944000
23    3.907000
24    7.944000
25    7.849000
26    9.285000
27    9.264000
28    9.801000
29    6.013703
30    4.701769
31    6.377626
32    6.169784
33    6.030051
34    5.557264
35    5.006668
36    4.876322
37    5.033069
38    5.069786
39    5.174292
40    5.019288
dtype: float64

In [26]:
df2['Percent_max'] = 100 * df2['GDP'] / df2['GDP'].max()

In [27]:
df2.head()

countrycode country currency_unit  year    GDP  net population growth  \
0         IND   India  Indian Rupee  1979    NaN             682.995354   
1         IND   India  Indian Rupee  1980  5.281               0.023364   
2         IND   India  Indian Rupee  1981  6.006               0.023510   
3         IND   India  Indian Rupee  1982  3.476               0.023560   
4         IND   India  Indian Rupee  1983  7.289               0.023475   

        CPI  employment rate     labsh        xr  ...     csh_r      pl_c  \
0       NaN       256.839111  0.709059  8.125791  ... -0.063782  0.190954   
1  11.34606         0.007102  0.038942 -0.032347  ... -0.235969  0.221119   
2  13.11255         0.004508 -0.027032  0.101181  ... -0.391245  0.024342   
3   7.89075         0.004125 -0.013325  0.092003  ...  0.640088  0.022520   
4  11.86807         0.003785  0.016143  0.068086  ... -0.435581  0.036162   

       pl_i      pl_g      pl_x      pl_m      pl_n      pl_k  GDP.1  \
0  0.224667  0.074652  0.292258  0.374884  0.140270  0.623519    NaN   
1  0.115094  0.211470  0.029731  0.119947  0.198038  0.040884  5.281   
2  0.200461  0.124758  0.062000 -0.101080  0.141719  0.044442  6.006   
3  0.062986  0.090714  0.009650 -0.020343  0.142196  0.070686  3.476   
4  0.053462  0.145769  0.073353 -0.117499  0.109214 -0.044686  7.289   

   Percent_max  
0          NaN  
1    53.882257  
2    61.279461  
3    35.465769  
4    74.369962  

[5 rows x 26 columns]

In [28]:
df2['Percent_max'] = np.round( df2['GDP'] / df2['GDP'].max(), decimals = 2)

In [29]:
df2.head()

countrycode country currency_unit  year    GDP  net population growth  \
0         IND   India  Indian Rupee  1979    NaN             682.995354   
1         IND   India  Indian Rupee  1980  5.281               0.023364   
2         IND   India  Indian Rupee  1981  6.006               0.023510   
3         IND   India  Indian Rupee  1982  3.476               0.023560   
4         IND   India  Indian Rupee  1983  7.289               0.023475   

        CPI  employment rate     labsh        xr  ...     csh_r      pl_c  \
0       NaN       256.839111  0.709059  8.125791  ... -0.063782  0.190954   
1  11.34606         0.007102  0.038942 -0.032347  ... -0.235969  0.221119   
2  13.11255         0.004508 -0.027032  0.101181  ... -0.391245  0.024342   
3   7.89075         0.004125 -0.013325  0.092003  ...  0.640088  0.022520   
4  11.86807         0.003785  0.016143  0.068086  ... -0.435581  0.036162   

       pl_i      pl_g      pl_x      pl_m      pl_n      pl_k  GDP.1  \
0  0.224667  0.074652  0.292258  0.374884  0.140270  0.623519    NaN   
1  0.115094  0.211470  0.029731  0.119947  0.198038  0.040884  5.281   
2  0.200461  0.124758  0.062000 -0.101080  0.141719  0.044442  6.006   
3  0.062986  0.090714  0.009650 -0.020343  0.142196  0.070686  3.476   
4  0.053462  0.145769  0.073353 -0.117499  0.109214 -0.044686  7.289   

   Percent_max  
0          NaN  
1         0.54  
2         0.61  
3         0.35  
4         0.74  

[5 rows x 26 columns]

In [30]:
df2['Percent_max'] *=100

In [31]:
df2.head()

countrycode country currency_unit  year    GDP  net population growth  \
0         IND   India  Indian Rupee  1979    NaN             682.995354   
1         IND   India  Indian Rupee  1980  5.281               0.023364   
2         IND   India  Indian Rupee  1981  6.006               0.023510   
3         IND   India  Indian Rupee  1982  3.476               0.023560   
4         IND   India  Indian Rupee  1983  7.289               0.023475   

        CPI  employment rate     labsh        xr  ...     csh_r      pl_c  \
0       NaN       256.839111  0.709059  8.125791  ... -0.063782  0.190954   
1  11.34606         0.007102  0.038942 -0.032347  ... -0.235969  0.221119   
2  13.11255         0.004508 -0.027032  0.101181  ... -0.391245  0.024342   
3   7.89075         0.004125 -0.013325  0.092003  ...  0.640088  0.022520   
4  11.86807         0.003785  0.016143  0.068086  ... -0.435581  0.036162   

       pl_i      pl_g      pl_x      pl_m      pl_n      pl_k  GDP.1  \
0  0.224667  0.074652  0.292258  0.374884  0.140270  0.623519    NaN   
1  0.115094  0.211470  0.029731  0.119947  0.198038  0.040884  5.281   
2  0.200461  0.124758  0.062000 -0.101080  0.141719  0.044442  6.006   
3  0.062986  0.090714  0.009650 -0.020343  0.142196  0.070686  3.476   
4  0.053462  0.145769  0.073353 -0.117499  0.109214 -0.044686  7.289   

   Percent_max  
0          NaN  
1         54.0  
2         61.0  
3         35.0  
4         74.0  

[5 rows x 26 columns]

In [32]:
#removing column
df2.drop('Percent_max',axis = 1)

countrycode country currency_unit  year       GDP  net population growth  \
0          IND   India  Indian Rupee  1979       NaN             682.995354   
1          IND   India  Indian Rupee  1980  5.281000               0.023364   
2          IND   India  Indian Rupee  1981  6.006000               0.023510   
3          IND   India  Indian Rupee  1982  3.476000               0.023560   
4          IND   India  Indian Rupee  1983  7.289000               0.023475   
5          IND   India  Indian Rupee  1984  3.821000               0.023224   
6          IND   India  Indian Rupee  1985  5.254000               0.022856   
7          IND   India  Indian Rupee  1986  4.777000               0.022458   
8          IND   India  Indian Rupee  1987  3.965000               0.022079   
9          IND   India  Indian Rupee  1988  9.628000               0.021700   
10         IND   India  Indian Rupee  1989  5.947000               0.021333   
11         IND   India  Indian Rupee  1990  5.534000               0.020978   
12         IND   India  Indian Rupee  1991  1.057000               0.020607   
13         IND   India  Indian Rupee  1992  5.482000               0.020234   
14         IND   India  Indian Rupee  1993  4.750000               0.019902   
15         IND   India  Indian Rupee  1994  6.659000               0.019622   
16         IND   India  Indian Rupee  1995  7.575000               0.019375   
17         IND   India  Indian Rupee  1996  7.550000               0.019133   
18         IND   India  Indian Rupee  1997  4.050000               0.018868   
19         IND   India  Indian Rupee  1998  6.184000               0.018567   
20         IND   India  Indian Rupee  1999  8.463000               0.018220   
21         IND   India  Indian Rupee  2000  3.975000               0.017838   
22         IND   India  Indian Rupee  2001  4.944000               0.017438   
23         IND   India  Indian Rupee  2002  3.907000               0.017039   
24         IND   India  Indian Rupee  2003  7.944000               0.016652   
25         IND   India  Indian Rupee  2004  7.849000               0.016284   
26         IND   India  Indian Rupee  2005  9.285000               0.015923   
27         IND   India  Indian Rupee  2006  9.264000               0.015577   
28         IND   India  Indian Rupee  2007  9.801000               0.015207   
29         IND   India  Indian Rupee  2008  6.013703               0.014757   
30         IND   India  Indian Rupee  2009  4.701769               0.014206   
31         IND   India  Indian Rupee  2010  6.377626               0.013595   
32         IND   India  Indian Rupee  2011  6.169784               0.012968   
33         IND   India  Indian Rupee  2012  6.030051               0.012391   
34         IND   India  Indian Rupee  2013  5.557264               0.011899   
35         IND   India  Indian Rupee  2014  5.006668               0.011523   
36         IND   India  Indian Rupee  2015  4.876322               0.011232   
37         IND   India  Indian Rupee  2016  5.033069               0.010964   
38         IND   India  Indian Rupee  2017  5.069786               0.010690   
39         IND   India  Indian Rupee  2018  5.174292               0.010432   
40         IND   India  Indian Rupee  2019  5.019288               0.010184   

          CPI  employment rate     labsh        xr  ...     csh_m      csh_r  \
0         NaN       256.839111  0.709059  8.125791  ... -0.027104  -0.063782   
1   11.346060         0.007102  0.038942 -0.032347  ...  0.311639  -0.235969   
2   13.112550         0.004508 -0.027032  0.101181  ...  0.171218  -0.391245   
3    7.890750         0.004125 -0.013325  0.092003  ... -0.227116   0.640088   
4   11.868070         0.003785  0.016143  0.068086  ...  0.568956  -0.435581   
5    8.318914         0.003513 -0.004469  0.125131  ... -0.186774   0.311368   
6    5.556426         0.003255 -0.023227  0.088551  ...  0.100199  -0.152234   
7    8.729712         0.004868 -0.004420  0.

In [33]:
df2.drop(0)

countrycode country currency_unit  year       GDP  net population growth  \
1          IND   India  Indian Rupee  1980  5.281000               0.023364   
2          IND   India  Indian Rupee  1981  6.006000               0.023510   
3          IND   India  Indian Rupee  1982  3.476000               0.023560   
4          IND   India  Indian Rupee  1983  7.289000               0.023475   
5          IND   India  Indian Rupee  1984  3.821000               0.023224   
6          IND   India  Indian Rupee  1985  5.254000               0.022856   
7          IND   India  Indian Rupee  1986  4.777000               0.022458   
8          IND   India  Indian Rupee  1987  3.965000               0.022079   
9          IND   India  Indian Rupee  1988  9.628000               0.021700   
10         IND   India  Indian Rupee  1989  5.947000               0.021333   
11         IND   India  Indian Rupee  1990  5.534000               0.020978   
12         IND   India  Indian Rupee  1991  1.057000               0.020607   
13         IND   India  Indian Rupee  1992  5.482000               0.020234   
14         IND   India  Indian Rupee  1993  4.750000               0.019902   
15         IND   India  Indian Rupee  1994  6.659000               0.019622   
16         IND   India  Indian Rupee  1995  7.575000               0.019375   
17         IND   India  Indian Rupee  1996  7.550000               0.019133   
18         IND   India  Indian Rupee  1997  4.050000               0.018868   
19         IND   India  Indian Rupee  1998  6.184000               0.018567   
20         IND   India  Indian Rupee  1999  8.463000               0.018220   
21         IND   India  Indian Rupee  2000  3.975000               0.017838   
22         IND   India  Indian Rupee  2001  4.944000               0.017438   
23         IND   India  Indian Rupee  2002  3.907000               0.017039   
24         IND   India  Indian Rupee  2003  7.944000               0.016652   
25         IND   India  Indian Rupee  2004  7.849000               0.016284   
26         IND   India  Indian Rupee  2005  9.285000               0.015923   
27         IND   India  Indian Rupee  2006  9.264000               0.015577   
28         IND   India  Indian Rupee  2007  9.801000               0.015207   
29         IND   India  Indian Rupee  2008  6.013703               0.014757   
30         IND   India  Indian Rupee  2009  4.701769               0.014206   
31         IND   India  Indian Rupee  2010  6.377626               0.013595   
32         IND   India  Indian Rupee  2011  6.169784               0.012968   
33         IND   India  Indian Rupee  2012  6.030051               0.012391   
34         IND   India  Indian Rupee  2013  5.557264               0.011899   
35         IND   India  Indian Rupee  2014  5.006668               0.011523   
36         IND   India  Indian Rupee  2015  4.876322               0.011232   
37         IND   India  Indian Rupee  2016  5.033069               0.010964   
38         IND   India  Indian Rupee  2017  5.069786               0.010690   
39         IND   India  Indian Rupee  2018  5.174292               0.010432   
40         IND   India  Indian Rupee  2019  5.019288               0.010184   

          CPI  employment rate     labsh        xr  ...      csh_r      pl_c  \
1   11.346060         0.007102  0.038942 -0.032347  ...  -0.235969  0.221119   
2   13.112550         0.004508 -0.027032  0.101181  ...  -0.391245  0.024342   
3    7.890750         0.004125 -0.013325  0.092003  ...   0.640088  0.022520   
4   11.868070         0.003785  0.016143  0.068086  ...  -0.435581  0.036162   
5    8.318914         0.003513 -0.004469  0.125131  ...   0.311368 -0.020696   
6    5.556426         0.003255 -0.023227  0.088551  ...  -0.152234 -0.007321   
7    8.729712         0.004868 -0.004420  0.019572  ...   0.336192  0.056895   
8    8.801135         0.004824  0.004842  0.027807  ...   0.281138  0.037346   
9    9.383466         0.004898 -0.003169  0

In [34]:
df2.head()

countrycode country currency_unit  year    GDP  net population growth  \
0         IND   India  Indian Rupee  1979    NaN             682.995354   
1         IND   India  Indian Rupee  1980  5.281               0.023364   
2         IND   India  Indian Rupee  1981  6.006               0.023510   
3         IND   India  Indian Rupee  1982  3.476               0.023560   
4         IND   India  Indian Rupee  1983  7.289               0.023475   

        CPI  employment rate     labsh        xr  ...     csh_r      pl_c  \
0       NaN       256.839111  0.709059  8.125791  ... -0.063782  0.190954   
1  11.34606         0.007102  0.038942 -0.032347  ... -0.235969  0.221119   
2  13.11255         0.004508 -0.027032  0.101181  ... -0.391245  0.024342   
3   7.89075         0.004125 -0.013325  0.092003  ...  0.640088  0.022520   
4  11.86807         0.003785  0.016143  0.068086  ... -0.435581  0.036162   

       pl_i      pl_g      pl_x      pl_m      pl_n      pl_k  GDP.1  \
0  0.224667  0.074652  0.292258  0.374884  0.140270  0.623519    NaN   
1  0.115094  0.211470  0.029731  0.119947  0.198038  0.040884  5.281   
2  0.200461  0.124758  0.062000 -0.101080  0.141719  0.044442  6.006   
3  0.062986  0.090714  0.009650 -0.020343  0.142196  0.070686  3.476   
4  0.053462  0.145769  0.073353 -0.117499  0.109214 -0.044686  7.289   

   Percent_max  
0          NaN  
1         54.0  
2         61.0  
3         35.0  
4         74.0  

[5 rows x 26 columns]

In [35]:
df2 = df2.drop('Percent_max',axis = 1)

In [36]:
df2.head()

countrycode country currency_unit  year    GDP  net population growth  \
0         IND   India  Indian Rupee  1979    NaN             682.995354   
1         IND   India  Indian Rupee  1980  5.281               0.023364   
2         IND   India  Indian Rupee  1981  6.006               0.023510   
3         IND   India  Indian Rupee  1982  3.476               0.023560   
4         IND   India  Indian Rupee  1983  7.289               0.023475   

        CPI  employment rate     labsh        xr  ...     csh_m     csh_r  \
0       NaN       256.839111  0.709059  8.125791  ... -0.027104 -0.063782   
1  11.34606         0.007102  0.038942 -0.032347  ...  0.311639 -0.235969   
2  13.11255         0.004508 -0.027032  0.101181  ...  0.171218 -0.391245   
3   7.89075         0.004125 -0.013325  0.092003  ... -0.227116  0.640088   
4  11.86807         0.003785  0.016143  0.068086  ...  0.568956 -0.435581   

       pl_c      pl_i      pl_g      pl_x      pl_m      pl_n      pl_k  GDP.1  
0  0.190954  0.224667  0.074652  0.292258  0.374884  0.140270  0.623519    NaN  
1  0.221119  0.115094  0.211470  0.029731  0.119947  0.198038  0.040884  5.281  
2  0.024342  0.200461  0.124758  0.062000 -0.101080  0.141719  0.044442  6.006  
3  0.022520  0.062986  0.090714  0.009650 -0.020343  0.142196  0.070686  3.476  
4  0.036162  0.053462  0.145769  0.073353 -0.117499  0.109214 -0.044686  7.289  

[5 rows x 25 columns]

In [37]:
df2.sort_values

AttributeError: module 'pandas' has no attribute 'sort_by'