In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
matrix = [(1,2,3),(4,5,6),(7,8,9)]

In [4]:
np_matrix = np.array(matrix)
print(np_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr = np.arange(0,101,2)
print(arr)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [6]:
arr0 = np.zeros((3,4),int)
print(arr0)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [7]:
arr1 = np.ones((3,2),dtype = int)
print(arr1)

[[1 1]
 [1 1]
 [1 1]]


In [29]:
lns = np.linspace(0,10,7);
print(lns)

[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]


In [9]:
idm = np.eye(3, dtype = int)
print(idm)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [10]:
randarr = np.random.rand(5,4)
print(randarr)

[[0.51576983 0.24300495 0.25974735 0.61789507]
 [0.5111082  0.25309544 0.37368615 0.28644207]
 [0.32294517 0.949335   0.14119008 0.34831274]
 [0.20406555 0.26430173 0.94593763 0.78580015]
 [0.01104008 0.01808685 0.25071716 0.34038195]]


In [11]:
randnarr = np.random.randn(2,3)
print(randnarr)

[[-0.41176654  1.26430856  0.42045083]
 [-1.16095855  0.60310112  0.35007994]]


In [12]:
ranint = np.random.randint(0,101,25)
print(ranint)

[93 24 40 27 22 81 84 69 98 42 45 45 69 80 95 84 51 20 86 60 55 36 71 25
  5]


In [13]:
rain = np.random.randint(1,25,(3,2))
print(rain)

[[ 1 24]
 [15  2]
 [ 6  4]]


In [14]:
np.random.seed(42)
ar = np.random.randint(0,59,8)
print(ar)

[38 51 28 14 42  7 20 38]


In [15]:
ar.reshape(2,4)

array([[38, 51, 28, 14],
       [42,  7, 20, 38]])

In [16]:
ar.dtype

dtype('int32')

In [17]:
ar.max()

51

In [18]:
ar.min()

7

In [19]:
ar.argmax()

1

In [20]:
ar.argmin()

5

In [21]:
slice_of_ar = ar[0:5]

In [22]:
print(slice_of_ar)

[38 51 28 14 42]


In [23]:
slice_of_ar[:] = 69
print(slice_of_ar)
print(ar)

[69 69 69 69 69]
[69 69 69 69 69  7 20 38]


In [24]:
arr = np.arange(0,31,2,int).reshape(4,4)
print(arr)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]]


In [25]:
np.sum(arr,axis=1)

array([ 12,  44,  76, 108])

In [26]:
matrixnp = np.arange(1,26,1,int).reshape(5,5)
print (matrixnp)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [27]:
mat = matrixnp[2:,1:]
print(mat)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [30]:
matrixnp[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [31]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 